export type CodeToken = { t: "ln" | "kw" | "fn" | "st" | "cm" | "pu"; v: string };

export const WHY_CODE_LINES: CodeToken[][] = [
  [{ t: "ln", v: "1" }, { t: "kw", v: "import" }, { t: "pu", v: " SwiftUI" }],
  [{ t: "ln", v: "2" }, { t: "kw", v: "import" }, { t: "pu", v: " Combine" }],
  [{ t: "ln", v: "3" }, { t: "pu", v: "" }],
  [{ t: "ln", v: "4" }, { t: "kw", v: "struct" }, { t: "fn", v: " DashboardView" }, { t: "pu", v: ": View {" }],
  [
    { t: "ln", v: "5" },
    { t: "pu", v: "  " },
    { t: "kw", v: "@State" },
    { t: "pu", v: " " },
    { t: "kw", v: "private var" },
    { t: "fn", v: " isLoaded" },
    { t: "pu", v: " = " },
    { t: "st", v: "false" },
  ],
  [
    { t: "ln", v: "6" },
    { t: "pu", v: "  " },
    { t: "kw", v: "@Published" },
    { t: "pu", v: " " },
    { t: "kw", v: "var" },
    { t: "fn", v: " users" },
    { t: "pu", v: ": [" },
    { t: "fn", v: "User" },
    { t: "pu", v: "] = []" },
  ],
  [{ t: "ln", v: "7" }, { t: "pu", v: "  " }],
  [
    { t: "ln", v: "8" },
    { t: "pu", v: "  " },
    { t: "kw", v: "var" },
    { t: "pu", v: " body: " },
    { t: "kw", v: "some" },
    { t: "pu", v: " View {" },
  ],
  [
    { t: "ln", v: "9" },
    { t: "pu", v: "    " },
    { t: "fn", v: "NavigationStack" },
    { t: "pu", v: " {" },
  ],
  [
    { t: "ln", v: "10" },
    { t: "pu", v: "      " },
    { t: "fn", v: "VStack" },
    { t: "pu", v: "(spacing: " },
    { t: "st", v: "16" },
    { t: "pu", v: ") {" },
  ],
  [{ t: "ln", v: "11" }, { t: "cm", v: "        // Hero section" }],
  [
    { t: "ln", v: "12" },
    { t: "pu", v: "        " },
    { t: "fn", v: "HeaderCard" },
    { t: "pu", v: "(title: " },
    { t: "st", v: '"Dashboard"' },
    { t: "pu", v: ")" },
  ],
];
