export type CodeToken = { t: "ln" | "kw" | "fn" | "st" | "cm" | "pu"; v: string };

const WHY_CODE_LINES_IPHONE: CodeToken[][] = [
  [{ t: "ln", v: "1" }, { t: "kw", v: "import" }, { t: "pu", v: " SwiftUI" }],
  [{ t: "ln", v: "2" }, { t: "kw", v: "import" }, { t: "pu", v: " Combine" }],
  [{ t: "ln", v: "3" }, { t: "pu", v: "" }],
  [{ t: "ln", v: "4" }, { t: "kw", v: "struct" }, { t: "fn", v: " DashboardView" }, { t: "pu", v: ": View {" }],
  [
    { t: "ln", v: "5" },
    { t: "pu", v: "  " },
    { t: "kw", v: "@State" },
    { t: "pu", v: " " },
    { t: "kw", v: "private var" },
    { t: "fn", v: " isLoaded" },
    { t: "pu", v: " = " },
    { t: "st", v: "false" },
  ],
  [
    { t: "ln", v: "6" },
    { t: "pu", v: "  " },
    { t: "kw", v: "@Published" },
    { t: "pu", v: " " },
    { t: "kw", v: "var" },
    { t: "fn", v: " users" },
    { t: "pu", v: ": [" },
    { t: "fn", v: "User" },
    { t: "pu", v: "] = []" },
  ],
  [{ t: "ln", v: "7" }, { t: "pu", v: "  " }],
  [
    { t: "ln", v: "8" },
    { t: "pu", v: "  " },
    { t: "kw", v: "var" },
    { t: "pu", v: " body: " },
    { t: "kw", v: "some" },
    { t: "pu", v: " View {" },
  ],
  [
    { t: "ln", v: "9" },
    { t: "pu", v: "    " },
    { t: "fn", v: "NavigationStack" },
    { t: "pu", v: " {" },
  ],
  [
    { t: "ln", v: "10" },
    { t: "pu", v: "      " },
    { t: "fn", v: "VStack" },
    { t: "pu", v: "(spacing: " },
    { t: "st", v: "16" },
    { t: "pu", v: ") {" },
  ],
  [{ t: "ln", v: "11" }, { t: "cm", v: "        // Hero section" }],
  [
    { t: "ln", v: "12" },
    { t: "pu", v: "        " },
    { t: "fn", v: "HeaderCard" },
    { t: "pu", v: "(title: " },
    { t: "st", v: '"Dashboard"' },
    { t: "pu", v: ")" },
  ],
];

const WHY_CODE_LINES_ANDROID: CodeToken[][] = [
  [{ t: "ln", v: "1" }, { t: "kw", v: "import" }, { t: "pu", v: " androidx.compose.runtime.*" }],
  [{ t: "ln", v: "2" }, { t: "kw", v: "import" }, { t: "pu", v: " androidx.compose.material3.*" }],
  [{ t: "ln", v: "3" }, { t: "pu", v: "" }],
  [
    { t: "ln", v: "4" },
    { t: "kw", v: "@Composable" },
    { t: "pu", v: " " },
    { t: "fn", v: "fun" },
    { t: "pu", v: " " },
    { t: "fn", v: "Dashboard" },
    { t: "pu", v: "() {" },
  ],
  [
    { t: "ln", v: "5" },
    { t: "pu", v: "  " },
    { t: "kw", v: "val" },
    { t: "pu", v: " " },
    { t: "fn", v: "state" },
    { t: "pu", v: " = " },
    { t: "fn", v: "remember" },
    { t: "pu", v: " { " },
    { t: "fn", v: "mutableStateOf" },
    { t: "pu", v: "(" },
    { t: "st", v: "0" },
    { t: "pu", v: ") }" },
  ],
  [{ t: "ln", v: "6" }, { t: "cm", v: "  // Material UI + fast iteration" }],
  [
    { t: "ln", v: "7" },
    { t: "pu", v: "  " },
    { t: "fn", v: "Scaffold" },
    { t: "pu", v: " { " },
    { t: "fn", v: "Text" },
    { t: "pu", v: "(" },
    { t: "st", v: "\"Hello Android\"" },
    { t: "pu", v: ") }" },
  ],
  [{ t: "ln", v: "8" }, { t: "pu", v: "}" }],
];

const WHY_CODE_LINES_FLUTTER: CodeToken[][] = [
  [{ t: "ln", v: "1" }, { t: "kw", v: "import" }, { t: "pu", v: " 'package:flutter/material.dart';" }],
  [{ t: "ln", v: "2" }, { t: "pu", v: "" }],
  [
    { t: "ln", v: "3" },
    { t: "kw", v: "class" },
    { t: "fn", v: " Dashboard" },
    { t: "pu", v: " " },
    { t: "kw", v: "extends" },
    { t: "pu", v: " " },
    { t: "fn", v: "StatelessWidget" },
    { t: "pu", v: " {" },
  ],
  [
    { t: "ln", v: "4" },
    { t: "pu", v: "  " },
    { t: "kw", v: "@override" },
  ],
  [
    { t: "ln", v: "5" },
    { t: "pu", v: "  " },
    { t: "fn", v: "Widget" },
    { t: "pu", v: " " },
    { t: "fn", v: "build" },
    { t: "pu", v: "(" },
    { t: "fn", v: "BuildContext" },
    { t: "pu", v: " context) {" },
  ],
  [
    { t: "ln", v: "6" },
    { t: "pu", v: "    " },
    { t: "kw", v: "return" },
    { t: "pu", v: " " },
    { t: "fn", v: "Scaffold" },
    { t: "pu", v: "(" },
    { t: "fn", v: "body" },
    { t: "pu", v: ": " },
    { t: "fn", v: "Center" },
    { t: "pu", v: "(" },
    { t: "fn", v: "child" },
    { t: "pu", v: ": " },
    { t: "fn", v: "Text" },
    { t: "pu", v: "(" },
    { t: "st", v: "'Hello Flutter'" },
    { t: "pu", v: ")))," },
  ],
  [{ t: "ln", v: "7" }, { t: "pu", v: "  }" }],
  [{ t: "ln", v: "8" }, { t: "pu", v: "}" }],
];

export const WHY_CODE_LINES_BY_SERVICE = {
  iphone: WHY_CODE_LINES_IPHONE,
  android: WHY_CODE_LINES_ANDROID,
  flutter: WHY_CODE_LINES_FLUTTER,
} as const;
